Added check of all arguments of the function.
HowProgrammingWorks/EventEmitter pull request #5
Opened 2017-08-27 12:06 UTC by NazarPonochevnyi

Added check of all arguments of the function, because the arguments are raised where they do not need.

2017-09-02 20:58 UTC, tshemsedinov requested changes

2017-09-02 20:58 UTC, tshemsedinov commented on JavaScript/4-usage.js
> +  if(name, data){
Use linter before PR, add spaces for code style `if (name, data) {`

2017-09-02 20:59 UTC, tshemsedinov commented on JavaScript/4-usage.js
> +  if(name, data){
Second issue: you use two values in `if`

2017-09-02 21:01 UTC, tshemsedinov commented
Why do we need to check all arguments?

2017-09-03 04:43 UTC, NazarPonochevnyi commented
Yes, I already understood that I had solved the problem poorly. Give me a little time, I'll fix it differently)

2017-09-04 16:30 UTC, NazarPonochevnyi commented
Sorry, but I don't know how fixed this problem. When I finded answer, I create new PR.

2017-09-04 16:30 UTC, closed without merging

2017-09-05 15:43 UTC, tshemsedinov commented
@NazarPonochevnyi you may reopen PR instead